# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Kranthi Kiran
tagline:             'Personalized Diary'
description:         'Project Lead at GEAR'
url:                 http://gearsystems.github.io
baseurl:             /kranthi/
paginate:            5

# About/contact
author:
  name:              Kranthi Kiran
  url:               https://twitter.com/Kranthi_Guduru
  email:             guduru.kranthikiran@gmail.com

# Custom vars
version:             1.0.0
